### ISSUE TITLE
Mysql2::Error: Table 'bookshelf_development.schema_migrations' doesn't exist

### ISSUE THREAD

**Issue by RemiBa** [hanami/bookshelf#4] opened 2017-05-16 07:34 UTC
I'm going through the getting started guide.
On chapter "Modeling Our Data With Entities" I execute following commands:

My-iMac:bookshelf myname$ bundle exec hanami generate model book
```
      create  lib/bookshelf/entities/book.rb
      create  lib/bookshelf/repositories/book_repository.rb
      create  db/migrations/20170516071624_create_books.rb
      create  spec/bookshelf/entities/book_spec.rb
      create  spec/bookshelf/repositories/book_repository_spec.rb
```
My-iMac:bookshelf myname$ bundle exec hanami db prepare
```
[hanami] [INFO] (0.000079s) SET @@wait_timeout = 2147483
[hanami] [INFO] (0.000119s) SET SQL_AUTO_IS_NULL=0
[hanami] [ERROR] Mysql2::Error: Table 'bookshelf_development.schema_migrations' doesn't exist: SELECT NULL AS `nil` FROM `schema_migrations` LIMIT 1
[hanami] [INFO] (0.060494s) CREATE TABLE `schema_migrations` (`filename` varchar(255) PRIMARY KEY)
[hanami] [ERROR] Mysql2::Error: Table 'bookshelf_development.schema_info' doesn't exist: SELECT NULL AS `nil` FROM `schema_info` LIMIT 1
[hanami] [INFO] (0.000283s) SELECT `filename` FROM `schema_migrations` ORDER BY `filename`
[hanami] [INFO] Begin applying migration 20170516071624_create_books.rb, direction: up
[hanami] [INFO] (0.015804s) CREATE TABLE `books` (`id` integer PRIMARY KEY AUTO_INCREMENT, `title` varchar(255) NOT NULL, `author` varchar(255) NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL)
[hanami] [INFO] (0.002129s) INSERT INTO `schema_migrations` (`filename`) VALUES ('20170516071624_create_books.rb')
[hanami] [INFO] Finished applying migration 20170516071624_create_books.rb, direction: up, took 0.018571 seconds
```

If I destroy the generated model, bundle exec hanami db prepare works properly (which is normal, the schema_migrations isn't being called as there are no migrations).

**Comment by mereghost** [comment] 2017-06-02 14:32
By the logs it seems to be working fine. The `error` entry is just a way to check if the table exists at all, then it proceeds to create it and run the needed migrations.

**Comment by cllns** [comment] 2021-06-30 16:08
Closing as a duplicate of https://github.com/hanami/hanami/issues/1087, which has been fixed in https://github.com/hanami/model/pull/620 (but hasn't been released yet).

**Closed by cllns** 2021-06-30 16:08 UTC
